[package]
name = "dengjen-grpc"
version = "0.2.0"
edition = "2021"
license.workspace = true

[lints]
workspace = true

[features]
default = ["espeak"]
espeak = ["dengjen-piper/espeak"]
ort-dylib = ["ort/load-dynamic"]

[dependencies]
async-stream = "0.3.5"
env_logger = "0.10.0"
log = "0.4.18"
dengjen-core = { version = "0.2.0", path = "../../dengjen/core" }
dengjen-synth = { version = "0.2.0", path = "../../dengjen/synth" }
dengjen-piper = { version = "0.2.0", path = "../../dengjen/models/piper" }
prost = "0.13.3"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.16"
tonic = "0.12.3"
xxhash-rust = { version = "0.8.12", features = ["xxh3"] }

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27"]

[build-dependencies]
tonic-build = "0.12.3"
