[package]
name = "dengjen-tts-piper"
version.workspace = true
edition = "2021"
license.workspace = true
description = "Piper neural TTS model backend for the dengjen-tts speech synthesis engine"
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[features]
default = ["tashkeel", "espeak"]
tashkeel = ["dep:dengjen-tashkeel"]
hebrew = ["dep:dengjen-hebrew-phonemizer"]
pinyin = ["dep:dengjen-pinyin-phonemizer"]

espeak = ["dep:dengjen-espeak-phonemizer"]


cuda = ["ort/cuda"]
coreml = ["ort/coreml"]
directml = ["ort/directml"]

[dependencies]
dengjen-espeak-phonemizer = { workspace = true, optional = true }
dengjen-hebrew-phonemizer = { workspace = true, optional = true }
dengjen-pinyin-phonemizer = { workspace = true, optional = true }
dengjen-tts-core.workspace = true
ndarray = "0.17"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.89"

[dependencies.dengjen-tashkeel]
version = "1.5.1"
default-features = false
features = ["ort", "rayon"]
optional = true

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27"]
