[package]
name = "dengjen-tts-python"
version = "0.2.0"
edition = "2021"
license.workspace = true

[lints]
workspace = true

[lib]
name = "pydengjen"
crate-type = ["cdylib"]

[features]
default = ["tashkeel", "espeak"]
ort-dylib = ["ort/load-dynamic"]
tashkeel = ["dep:libtashkeel_core", "dengjen-tts-piper/tashkeel"]
espeak = ["dep:espeak-phonemizer", "dengjen-tts-piper/espeak"]
cuda = ["dengjen-tts-piper/cuda"]
coreml = ["dengjen-tts-piper/coreml"]
directml = ["dengjen-tts-piper/directml"]

[dependencies]
espeak-phonemizer = { path = "../../text/espeak-phonemizer", optional = true }
dengjen-tts-core = { path = "../../dengjen/core" }
dengjen-tts = { path = "../../dengjen/synth" }
dengjen-tts-piper = { path = "../../dengjen/models/piper", default-features = false }
once_cell = "1.18.0"

[dependencies.libtashkeel_core]
version = "1.5.0"
default-features = false
features = ["ort", "rayon"]
optional = true

[dependencies.pyo3]
version = "0.29.1"
features = ["extension-module", "abi3-py39"]

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27"]

[build-dependencies]
fs_extra = "1.3.0"
