[package]
name = "hebrew-phonemizer"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lints]
workspace = true

[dependencies]
dengjen-tts-core = { path = "../../dengjen/core" }
ndarray = "0.17"
regex = "1.9.3"
unicode-normalization = "0.1"

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27"]
