[package]
name = "libdengjen"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
name = "libdengjen"
crate-type = ["staticlib", "cdylib"]

[features]
default = ["piper", "espeak"]
piper = ["dep:dengjen-piper", "dep:ort"]
espeak = ["dengjen-piper/espeak"]
ort-dylib = ["ort/load-dynamic"]

[dependencies]
dengjen-core = { version = "0.2.0", path = "../../dengjen/core" }
dengjen-synth = { version = "0.2.0", path = "../../dengjen/synth" }
ffi-support = "0.4.4"
libc = "0.2.150"

[dependencies.dengjen-piper]
version = "0.2.0"
path = "../../dengjen/models/piper"
optional = true

[dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27"]
optional = true

[target.'cfg(target_os="android")'.dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27", "nnapi"]
optional = true

[target.'cfg(target_os="ios")'.dependencies.ort]
version = "2.0.0-rc.13"
default-features = false
features = ["std", "ndarray", "tracing", "download-binaries", "tls-rustls", "copy-dylibs", "api-27", "coreml"]
optional = true

[build-dependencies]
cbindgen = "0.29.4"
