[workspace]

[package]
name = "espeak-phonemizer-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"

[dependencies.dengjen-espeak-phonemizer]
path = ".."

[[bin]]
name = "text_to_phonemes"
path = "fuzz_targets/text_to_phonemes.rs"
test = false
doc = false
bench = false
