name: Project sync

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]

permissions: {}

jobs:
  sync:
    uses: ZirekHQ/.github/.github/workflows/project-sync.yml@b0d40ce73a68d6babfdb6d82425842d51c2ed575 # main
    secrets:
      PROJECT_SYNC_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
